name: learn-github-actions
on:
  push:
  pull_request:
    branches:
      - "main"
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Norm
        run: ./norm.sh
      - name: Test
        if: github.event_name == 'pull_request' # only run for merges
        run: ./tests
